// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PricesComparation.Models.Context;

namespace PricesComparation.Migrations
{
    [DbContext(typeof(PricesComparationContext))]
    partial class PricesComparationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("PricesComparation.Models.Address", b =>
                {
                    b.Property<int>("AdressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("District")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("State")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Street")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AdressId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("PricesComparation.Models.Brand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("PricesComparation.Models.PriceRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ProductShopId")
                        .HasColumnType("int");

                    b.HasKey("RecordId");

                    b.HasIndex("ProductShopId");

                    b.ToTable("PriceRecords");
                });

            modelBuilder.Entity("PricesComparation.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("BrandId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long?>("ShopId")
                        .HasColumnType("bigint");

                    b.Property<string>("Typed")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ShopId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("PricesComparation.Models.ProductShop", b =>
                {
                    b.Property<int>("ProductShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<DateTime>("PriceDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ShopId")
                        .HasColumnType("bigint");

                    b.HasKey("ProductShopId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShopId");

                    b.ToTable("ProductShops");
                });

            modelBuilder.Entity("PricesComparation.Models.Shop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("Shop");
                });

            modelBuilder.Entity("PricesComparation.Models.PriceRecord", b =>
                {
                    b.HasOne("PricesComparation.Models.ProductShop", "ProductShop")
                        .WithMany("Records")
                        .HasForeignKey("ProductShopId");

                    b.Navigation("ProductShop");
                });

            modelBuilder.Entity("PricesComparation.Models.Product", b =>
                {
                    b.HasOne("PricesComparation.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId");

                    b.HasOne("PricesComparation.Models.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId");

                    b.Navigation("Brand");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("PricesComparation.Models.ProductShop", b =>
                {
                    b.HasOne("PricesComparation.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("PricesComparation.Models.Shop", "Shop")
                        .WithMany("Products")
                        .HasForeignKey("ShopId");

                    b.Navigation("Product");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("PricesComparation.Models.Shop", b =>
                {
                    b.HasOne("PricesComparation.Models.Address", "Address")
                        .WithOne()
                        .HasForeignKey("PricesComparation.Models.Shop", "AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("PricesComparation.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PricesComparation.Models.ProductShop", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("PricesComparation.Models.Shop", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
